name: spotlight
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.1.0
  share_plus: ^11.0.0
  image_picker: ^1.1.2
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.0
  video_player: ^2.9.5
  photo_manager: ^3.7.1
  photo_manager_image_provider: ^2.2.0
  provider: ^6.1.5
  # video_trimmer: ^2.1.0
  # ffmpeg_kit_flutter_new: ^2.0.0
  # flutter_native_video_trimmer: ^1.1.9
  # get_thumbnail_video: ^0.7.3
  transparent_image: ^2.0.1
  # intl: ^0.18.1
  # image: ^4.5.4
  # easy_video_editor: ^0.1.2
  # video_editor: 2.1.0
  video_thumbnail: ^0.5.6
  country_state_city_pro: 
    path: packages/country_state_city_pro-0.0.6
  intl: ^0.20.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
